stages:
  - build
  - test
  - security-quality

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  POSTGRES_DB: "pgminibank"
  POSTGRES_USER: "minibank"
  POSTGRES_PASSWORD: "minibank1234"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  SECRET_DETECTION_ENABLED: 'true'
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SPRING_PROFILES_ACTIVE: "test"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/pgminibank"

cache:
  paths:
    - .m2/repository/
    - src/main/frontend/node_modules/
    - .sonar/cache/

# Security scanning templates
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Combined build and frontend stage
build-and-frontend:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  before_script:
    # Install Node.js for frontend build
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    # Build frontend
    - cd src/main/frontend
    - npm install
    - npm run build
    - cd ../../../
  script:
    # Validate and compile
    - mvn $MAVEN_CLI_OPTS dependency:resolve-sources
    - mvn $MAVEN_CLI_OPTS compile
    # Build final package
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      - src/main/resources/static/css/output.css
      - target/classes/
    expire_in: 1 week
  only:
    - main

# Consolidated test stage with all test types
comprehensive-tests:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  services:
    - name: postgres:17
      alias: postgres
    - name: docker:dind
      alias: docker
  dependencies:
    - build-and-frontend
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
    SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
  before_script:
    # Install required packages
    - apt-get update -qq && apt-get install -y -qq postgresql-client docker.io
    # Wait for PostgreSQL
    - until pg_isready -h postgres -p 5432; do echo "Waiting for postgres..."; sleep 2; done
    # Verify Docker for functional tests
    - docker info
    # Enable container reuse
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
  script:
    # Run all test types in sequence with coverage and SonarCloud analysis (includes security scan results)
    - echo "=== Running All Tests ==="
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.projectKey=tazkia.ac.id_aplikasi-minibank
    - mvn $MAVEN_CLI_OPTS jacoco:report
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
    paths:
      - target/surefire-reports/
      - target/karate-reports/
      - target/selenium-recordings/
      - target/site/jacoco/
    expire_in: 1 week
  coverage: '/Total.*?([0-9]{1,3})%/'
  only:
    - main

# Override security templates to run in test stage
sast:
  stage: test

secret_detection:
  stage: test

